### ISSUE TITLE
Log Fetcher: admin.hlx.page login state is not correctly/reliably conveyed to the user

### ISSUE THREAD

**Issue by shsteimer** [adobe/helix-tools-website#34]
### Expected Behaviour

If the user is authenticated against admin.hlx.live and in a valid site role, they should not get a login message

### Actual Behaviour

If the user is logged in, but not logged into sidekick, they get an error message.

### Reproduce Scenario (including but not limited to)

Sent this to @amol-anand in a DM with various reproduction scenarios, that I find to be confusing/inconsistent. Some/all of these may just be me not understanding.

```
Hey, I'm still confused on how the authentication works for the log viewer.

**Flow 1**

1. in a new browser window, go to https://tools.aem.live/tools/log-viewer/index.html and put in https://main--<byom site>--aemsites.aem.live/ and submit
2. get a 401, tells me login via sidekick
3. go to https://admin.hlx.page/login and login
4. log viewer still gives me a 401

Why doesn't this work? Is logging into sidekick and logging into admin service fundamentally different?

**Flow 2**

1. in a new browser window, go to https://tools.aem.live/tools/log-viewer/index.html and put in https://main--<byom site>--aemsites.aem.live/ and submit
2. get a 401, tells me login via sidekick
3. got to https://main--<byom site>--aemsites.aem.live/ and login with sidekick
4. log viewer no longer 401s, but if I click on a code link referenced from a log that gives me a 401
5. now go to https://admin.hlx.page/login and login
6. now the code link works

why is this different than above? aren't logging into sidekick and logging into admin service fundamentally the same thing?

**Flow 3, a combo of both:**

1. in a new browser window, go to https://tools.aem.live/tools/log-viewer/index.html and put in https://main--<byom site>--aemsites.aem.live/ and submit
2. get a 401, tells me login via sidekick
3. go to https://admin.hlx.page/login and login
4. log viewer still gives me a 401
5. go to https://main--<byom site>--aemsites.aem.live/ sidekick tells me I am logged in
6. log viewer still gives me 401

```

#### Sample Code that illustrates the problem

https://github.com/adobe/helix-tools-website/blob/main/tools/log-viewer/scripts.js#L375

I think adding `{ credentials: 'include' }` to that will fix it (but not confident enough that there aren't other security considerations here around that or I'd just raise a PR)

**Comment by amol-anand** [comment]
We removed `{ credentials: 'include' }` specifically because we don't want to transmit those credentials from other logged in sessions across domains.

Re: how logging in via sidekick and admin.hlx.page are different, I don't fully understand what is going on in the backend to answer that. Will dig in and figure it out. But until then, maybe @fkakatie / @rofe can help shed some light on it?

**Comment by rofe** [comment]
We moved away from cookie-based auth in tools (for security reasons, we decided to set the cookie to `Same-Site` to avoid abuse) and to only support log in via sidekick. The sidekick then sends the access token in an `x-auth-token` header with every fetch request to admin.
